backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images # Media files will be stored in the repo under static/
public_folder: /images # The src attribute for uploaded media will begin with static/

collections:
  - name: "project" # Used in routes, e.g., /admin/collections/project
    label: "Project" # Used in the UI
    folder: "static/_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Github", name: "github", widget: "string", required: false }
      - { label: "Demo", name: "demo", widget: "string", required: false }
  - name: "profile" # Used in routes, e.g., /admin/collections/skill
    label: "Profile" # Used in the UI
    file: "static/profile.yml" # The path to the folder where the documents are stored
    identifier-field: name
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Skills", name: "skills", widget: "list" }
